---

- name: create k8s repo centos
  yum_repository:
    name: Kubernetes
    description: k8s repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    gpgcheck: yes
    enabled: yes
    #exclude: kubelet,kubeadm,kubectl
  when: k8s_package_version is defined

# Set SELinux in permissive mode (effectively disabling it)
- name: Set setenforce 0
  command: "setenforce 0"
  when: k8s_package_version is defined

# Set SELinux in permissive mode (effectively disabling it)
- name: Set SELinux in permissive mode
  command: "sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"
  when: k8s_package_version is defined
  
  
# using this to avoid issue https://github.com/ansible/ansible/issues/20711
#- name: make cache to import gpg keys
#  command: "yum -q makecache -y --disablerepo='*' --enablerepo='Kubernetes'"
#  when: k8s_package_version is defined
